server:
  port: 9001
spring:
  application:
    name: cloud-nacos-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.32.134:3306/nacos_config?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.32.134:8848
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xuqing.springcloud.entities

management:
  endpoints:
    web:
      exposure:
        include: '*'
